# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jeff Macaluso
email: macaluso.jeff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello and welcome to my github page!  This is a place for showcasing my personal projects,
   the code I use for competitions, and so on.  I'll have more in my regular github,
   so check that out if you want to see other projects that aren't fully complete.
   I believe in sharing information with others, so feel free to reach out with
    any questions or comments!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MacalusoJeff
linkedin_username: macalusojeff
github_username:  JeffMacaluso

# Build settings
markdown: kramdown
# theme: minima
remote_theme: "mmistakes/minimal-mistakes"
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
